name: Build zipapp

# Manual run for setup/testing
on: workflow_dispatch
#on:
#  release:
#    types: [published]

jobs:
  build:
    name: Build zipapp
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.8"  # build with oldest supported python
    - name: Build the Zipapp
      run: >-
        python3 scripts/build_zipapp.py
    - name: Store the built zipapp
      uses: actions/upload-artifact@v4
      with:
        name: pythonfinder-zipapp
        path: dist/
